#!/bin/bash
TEMPLATE=$(find . -name AutoArgumentsDecodable.swifttemplate | head -1)
CORECLI_SOURCES=$(echo ${TEMPLATE:?} | sed 's/AutoArgumentsDecodable.swifttemplate//')
YOUR_SOURCE=Sources/ghaw
OUT=Sources/ghaw/zzz.Sourcery.out.swift
./Pods/Sourcery/bin/sourcery --sources "$YOUR_SOURCE" --sources ${CORECLI_SOURCES} --templates "$TEMPLATE" --output "$OUT"
